<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = array(
            array("id"=>"1","utc"=>"4","region"=>"South Asia","continent"=>"Asia","name"=>"Afghanistan"),
            array("id"=>"2","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Albania"),
            array("id"=>"3","utc"=>"1","region"=>"Northern Africa","continent"=>"Africa","name"=>"Algeria"),
            array("id"=>"4","utc"=>"-11","region"=>"Pacific","continent"=>"Oceania","name"=>"American Samoa"),
            array("id"=>"5","utc"=>"1","region"=>"South West Europe","continent"=>"Europe","name"=>"Andorra"),
            array("id"=>"6","utc"=>"1","region"=>"Southern Africa","continent"=>"Africa","name"=>"Angola"),
            array("id"=>"7","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Anguilla"),
            array("id"=>"8","utc"=>"0","region"=>"Undecided","continent"=>"Undecided","name"=>"Antarctica"),
            array("id"=>"9","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Antigua and Barbuda"),
            array("id"=>"10","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Argentina"),
            array("id"=>"11","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"Armenia"),
            array("id"=>"12","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Aruba"),
            array("id"=>"13","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Australia"),
            array("id"=>"14","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Austria"),
            array("id"=>"15","utc"=>"4","region"=>"South Asia","continent"=>"Asia","name"=>"Azerbaijan"),
            array("id"=>"16","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Bahamas"),
            array("id"=>"17","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Bahrain"),
            array("id"=>"18","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"Bangladesh"),
            array("id"=>"19","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Barbados"),
            array("id"=>"20","utc"=>"3","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Belarus"),
            array("id"=>"21","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Belgium"),
            array("id"=>"22","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Belize"),
            array("id"=>"23","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Benin"),
            array("id"=>"24","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Bermuda"),
            array("id"=>"25","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"Bhutan"),
            array("id"=>"26","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Bolivia"),
            array("id"=>"27","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Bosnia and Herzegovina"),
            array("id"=>"28","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Botswana"),
            array("id"=>"29","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Brazil"),
            array("id"=>"30","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"British Indian Ocean Territory"),
            array("id"=>"31","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"British Virgin Islands"),
            array("id"=>"32","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Brunei"),
            array("id"=>"33","utc"=>"2","region"=>"South East Europe","continent"=>"Europe","name"=>"Bulgaria"),
            array("id"=>"34","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Burkina Faso"),
            array("id"=>"35","utc"=>"2","region"=>"Central Africa","continent"=>"Africa","name"=>"Burundi"),
            array("id"=>"36","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Cambodia"),
            array("id"=>"37","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Cameroon"),
            array("id"=>"38","utc"=>"-5","region"=>"North America","continent"=>"Americas","name"=>"Canada"),
            array("id"=>"39","utc"=>"-1","region"=>"Western Africa","continent"=>"Africa","name"=>"Cape Verde"),
            array("id"=>"40","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Cayman Islands"),
            array("id"=>"41","utc"=>"1","region"=>"Central Africa","continent"=>"Africa","name"=>"Central African Republic"),
            array("id"=>"42","utc"=>"1","region"=>"Central Africa","continent"=>"Africa","name"=>"Chad"),
            array("id"=>"43","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Chile"),
            array("id"=>"44","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"China"),
            array("id"=>"45","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Christmas Island"),
            array("id"=>"46","utc"=>"6","region"=>"South East Asia","continent"=>"Asia","name"=>"Cocos Islands"),
            array("id"=>"47","utc"=>"-5","region"=>"South America","continent"=>"Americas","name"=>"Colombia"),
            array("id"=>"48","utc"=>"3","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Comoros"),
            array("id"=>"49","utc"=>"-10","region"=>"Pacific","continent"=>"Oceania","name"=>"Cook Islands"),
            array("id"=>"50","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Costa Rica"),
            array("id"=>"51","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Croatia"),
            array("id"=>"52","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Cuba"),
            array("id"=>"53","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Curacao"),
            array("id"=>"54","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Cyprus"),
            array("id"=>"55","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Czech Republic"),
            array("id"=>"56","utc"=>"1","region"=>"West Indies","continent"=>"Americas","name"=>"Democratic Republic of the Congo"),
            array("id"=>"57","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Denmark"),
            array("id"=>"58","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Djibouti"),
            array("id"=>"59","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Dominica"),
            array("id"=>"60","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Dominican Republic"),
            array("id"=>"61","utc"=>"9","region"=>"Pacific","continent"=>"Oceania","name"=>"East Timor"),
            array("id"=>"62","utc"=>"-5","region"=>"South America","continent"=>"Americas","name"=>"Ecuador"),
            array("id"=>"63","utc"=>"2","region"=>"Northern Africa","continent"=>"Africa","name"=>"Egypt"),
            array("id"=>"64","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"El Salvador"),
            array("id"=>"65","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Equatorial Guinea"),
            array("id"=>"66","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Eritrea"),
            array("id"=>"67","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Estonia"),
            array("id"=>"68","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Ethiopia"),
            array("id"=>"69","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Falkland Islands"),
            array("id"=>"70","utc"=>"0","region"=>"Northern Europe","continent"=>"Europe","name"=>"Faroe Islands"),
            array("id"=>"71","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Fiji"),
            array("id"=>"72","utc"=>"2","region"=>"Northern Europe","continent"=>"Europe","name"=>"Finland"),
            array("id"=>"73","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"France"),
            array("id"=>"74","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"French Guiana"),
            array("id"=>"75","utc"=>"-10","region"=>"Pacific","continent"=>"Oceania","name"=>"French polynesia"),
            array("id"=>"76","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Gabon"),
            array("id"=>"77","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Gambia"),
            array("id"=>"78","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"Georgia"),
            array("id"=>"79","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Germany"),
            array("id"=>"80","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Ghana"),
            array("id"=>"81","utc"=>"1","region"=>"South West Europe","continent"=>"Europe","name"=>"Gibraltar"),
            array("id"=>"82","utc"=>"2","region"=>"South East Europe","continent"=>"Europe","name"=>"Greece"),
            array("id"=>"83","utc"=>"-4","region"=>"North America","continent"=>"Americas","name"=>"Greenland"),
            array("id"=>"84","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Grenada"),
            array("id"=>"85","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Guam"),
            array("id"=>"86","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Guatemala"),
            array("id"=>"87","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Guernsey"),
            array("id"=>"88","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Guinea"),
            array("id"=>"89","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Guinea-Bissau"),
            array("id"=>"90","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Guyana"),
            array("id"=>"91","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Haiti"),
            array("id"=>"92","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Honduras"),
            array("id"=>"93","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"Hong Kong"),
            array("id"=>"94","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Hungary"),
            array("id"=>"95","utc"=>"0","region"=>"Northern Europe","continent"=>"Europe","name"=>"Iceland"),
            array("id"=>"96","utc"=>"5","region"=>"South Asia","continent"=>"Asia","name"=>"India"),
            array("id"=>"97","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Indonesia"),
            array("id"=>"98","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Iran"),
            array("id"=>"99","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Iraq"),
            array("id"=>"100","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Ireland"),
            array("id"=>"101","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Isle of Man"),
            array("id"=>"102","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Israel"),
            array("id"=>"103","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Italy"),
            array("id"=>"104","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Ivory Coast"),
            array("id"=>"105","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Jamaica"),
            array("id"=>"106","utc"=>"9","region"=>"East Asia","continent"=>"Asia","name"=>"Japan"),
            array("id"=>"107","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Jersey"),
            array("id"=>"108","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Jordan"),
            array("id"=>"109","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Kazakhstan"),
            array("id"=>"110","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Kenya"),
            array("id"=>"111","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Kiribati"),
            array("id"=>"112","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Kosovo"),
            array("id"=>"113","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Kuwait"),
            array("id"=>"114","utc"=>"6","region"=>"Central Asia","continent"=>"Asia","name"=>"Kyrgyzstan"),
            array("id"=>"115","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Laos"),
            array("id"=>"116","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Latvia"),
            array("id"=>"117","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Lebanon"),
            array("id"=>"118","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Lesotho"),
            array("id"=>"119","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Liberia"),
            array("id"=>"120","utc"=>"2","region"=>"Northern Africa","continent"=>"Africa","name"=>"Libya"),
            array("id"=>"121","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Liechtenstein"),
            array("id"=>"122","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Lithuania"),
            array("id"=>"123","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Luxembourg"),
            array("id"=>"124","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"Macao"),
            array("id"=>"125","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Macedonia"),
            array("id"=>"126","utc"=>"3","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Madagascar"),
            array("id"=>"127","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Malawi"),
            array("id"=>"128","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Malaysia"),
            array("id"=>"129","utc"=>"5","region"=>"South Asia","continent"=>"Asia","name"=>"Maldives"),
            array("id"=>"130","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Mali"),
            array("id"=>"131","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Malta"),
            array("id"=>"132","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Marshall Islands"),
            array("id"=>"133","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Mauritania"),
            array("id"=>"134","utc"=>"4","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Mauritius"),
            array("id"=>"135","utc"=>"3","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Mayotte"),
            array("id"=>"136","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Mexico"),
            array("id"=>"137","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"Micronesia"),
            array("id"=>"138","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Moldova"),
            array("id"=>"139","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Monaco"),
            array("id"=>"140","utc"=>"7","region"=>"Northern Asia","continent"=>"Asia","name"=>"Mongolia"),
            array("id"=>"141","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Montenegro"),
            array("id"=>"142","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Montserrat"),
            array("id"=>"143","utc"=>"0","region"=>"Northern Africa","continent"=>"Africa","name"=>"Morocco"),
            array("id"=>"144","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Mozambique"),
            array("id"=>"145","utc"=>"6","region"=>"South East Asia","continent"=>"Asia","name"=>"Myanmar"),
            array("id"=>"146","utc"=>"1","region"=>"Southern Africa","continent"=>"Africa","name"=>"Namibia"),
            array("id"=>"147","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Nauru"),
            array("id"=>"148","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"Nepal"),
            array("id"=>"149","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Netherlands"),
            array("id"=>"150","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Netherlands Antilles"),
            array("id"=>"151","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"New Caledonia"),
            array("id"=>"152","utc"=>"-11","region"=>"Pacific","continent"=>"Oceania","name"=>"New Zealand"),
            array("id"=>"153","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Nicaragua"),
            array("id"=>"154","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Niger"),
            array("id"=>"155","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Nigeria"),
            array("id"=>"156","utc"=>"-11","region"=>"Pacific","continent"=>"Oceania","name"=>"Niue"),
            array("id"=>"157","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"North Korea"),
            array("id"=>"158","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Northern Mariana Islands"),
            array("id"=>"159","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Norway"),
            array("id"=>"160","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"Oman"),
            array("id"=>"161","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Pakistan"),
            array("id"=>"162","utc"=>"9","region"=>"Pacific","continent"=>"Oceania","name"=>"Palau"),
            array("id"=>"163","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Palestine"),
            array("id"=>"164","utc"=>"-5","region"=>"Central America","continent"=>"Americas","name"=>"Panama"),
            array("id"=>"165","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Papua New Guinea"),
            array("id"=>"166","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Paraguay"),
            array("id"=>"167","utc"=>"-5","region"=>"South America","continent"=>"Americas","name"=>"Peru"),
            array("id"=>"168","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Philippines"),
            array("id"=>"169","utc"=>"-8","region"=>"Pacific","continent"=>"Oceania","name"=>"Pitcairn"),
            array("id"=>"170","utc"=>"1","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Poland"),
            array("id"=>"171","utc"=>"-1","region"=>"South West Europe","continent"=>"Europe","name"=>"Portugal"),
            array("id"=>"172","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Puerto Rico"),
            array("id"=>"173","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Qatar"),
            array("id"=>"174","utc"=>"1","region"=>"Central Africa","continent"=>"Africa","name"=>"Republic of the Congo"),
            array("id"=>"175","utc"=>"4","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Reunion"),
            array("id"=>"176","utc"=>"2","region"=>"South East Europe","continent"=>"Europe","name"=>"Romania"),
            array("id"=>"177","utc"=>"3","region"=>"Northern Asia","continent"=>"Asia","name"=>"Russia"),
            array("id"=>"178","utc"=>"2","region"=>"Central Asia","continent"=>"Africa","name"=>"Rwanda"),
            array("id"=>"179","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"Saint Barthelemy"),
            array("id"=>"180","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Saint Helena"),
            array("id"=>"181","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Saint Kitts and Nevis"),
            array("id"=>"182","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Saint Lucia"),
            array("id"=>"183","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"Saint Martin"),
            array("id"=>"184","utc"=>"-3","region"=>"Undecided","continent"=>"Americas","name"=>"Saint Pierre and Miquelon"),
            array("id"=>"185","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Saint Vincent and the Grenadines"),
            array("id"=>"186","utc"=>"13","region"=>"Pacific","continent"=>"Oceania","name"=>"Samoa"),
            array("id"=>"187","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"San Marino"),
            array("id"=>"188","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Sao Tome and Principe"),
            array("id"=>"189","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Saudi Arabia"),
            array("id"=>"190","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Senegal"),
            array("id"=>"191","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Serbia"),
            array("id"=>"192","utc"=>"4","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Seychelles"),
            array("id"=>"193","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Sierra Leone"),
            array("id"=>"194","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Singapore"),
            array("id"=>"195","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"Sint Maarten"),
            array("id"=>"196","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Slovakia"),
            array("id"=>"197","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Slovenia"),
            array("id"=>"198","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"Solomon Islands"),
            array("id"=>"199","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Somalia"),
            array("id"=>"200","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"South Africa"),
            array("id"=>"201","utc"=>"9","region"=>"East Asia","continent"=>"Asia","name"=>"South Korea"),
            array("id"=>"202","utc"=>"3","region"=>"Northern Africa","continent"=>"Africa","name"=>"South Sudan"),
            array("id"=>"203","utc"=>"1","region"=>"South West Europe","continent"=>"Europe","name"=>"Spain"),
            array("id"=>"204","utc"=>"5","region"=>"South Asia","continent"=>"Asia","name"=>"Sri Lanka"),
            array("id"=>"205","utc"=>"3","region"=>"Northern Africa","continent"=>"Africa","name"=>"Sudan"),
            array("id"=>"206","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Suriname"),
            array("id"=>"207","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Svalbard and Jan Mayen"),
            array("id"=>"208","utc"=>"2","region"=>"Northern Africa","continent"=>"Africa","name"=>"Swaziland"),
            array("id"=>"209","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Sweden"),
            array("id"=>"210","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Switzerland"),
            array("id"=>"211","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Syria"),
            array("id"=>"212","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"Taiwan"),
            array("id"=>"213","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Tajikistan"),
            array("id"=>"214","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Tanzania"),
            array("id"=>"215","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Thailand"),
            array("id"=>"216","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Togo"),
            array("id"=>"217","utc"=>"13","region"=>"Pacific","continent"=>"Oceania","name"=>"Tokelau"),
            array("id"=>"218","utc"=>"13","region"=>"Pacific","continent"=>"Oceania","name"=>"Tonga"),
            array("id"=>"219","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Trinidad and Tobago"),
            array("id"=>"220","utc"=>"1","region"=>"Northern Africa","continent"=>"Africa","name"=>"Tunisia"),
            array("id"=>"221","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Turkey"),
            array("id"=>"222","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Turkmenistan"),
            array("id"=>"223","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Turks and Caicos Islands"),
            array("id"=>"224","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Tuvalu"),
            array("id"=>"225","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"U.S. Virgin Islands"),
            array("id"=>"226","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Uganda"),
            array("id"=>"227","utc"=>"3","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Ukraine"),
            array("id"=>"228","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"United Arab Emirates"),
            array("id"=>"229","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"United Kingdom"),
            array("id"=>"230","utc"=>"-5","region"=>"North America","continent"=>"Americas","name"=>"United States"),
            array("id"=>"231","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Uruguay"),
            array("id"=>"232","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Uzbekistan"),
            array("id"=>"233","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"Vanuatu"),
            array("id"=>"234","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Vatican"),
            array("id"=>"235","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Venezuela"),
            array("id"=>"236","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Vietnam"),
            array("id"=>"237","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Wallis and Futuna"),
            array("id"=>"238","utc"=>"0","region"=>"Northern Africa","continent"=>"Africa","name"=>"Western Sahara"),
            array("id"=>"239","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Yemen"),
            array("id"=>"240","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Zambia"),
            array("id"=>"241","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Zimbabwe")
        );
        DB::table('countries')->insert($countries);
    }
}
