<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();
        $countries = array(
            array("country_id"=>"1","utc"=>"4","region"=>"South Asia","continent"=>"Asia","name"=>"Afghanistan"),
            array("country_id"=>"2","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Albania"),
            array("country_id"=>"3","utc"=>"1","region"=>"Northern Africa","continent"=>"Africa","name"=>"Algeria"),
            array("country_id"=>"4","utc"=>"-11","region"=>"Pacific","continent"=>"Oceania","name"=>"American Samoa"),
            array("country_id"=>"5","utc"=>"1","region"=>"South West Europe","continent"=>"Europe","name"=>"Andorra"),
            array("country_id"=>"6","utc"=>"1","region"=>"Southern Africa","continent"=>"Africa","name"=>"Angola"),
            array("country_id"=>"7","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Anguilla"),
            array("country_id"=>"8","utc"=>"0","region"=>"Undecided","continent"=>"Undecided","name"=>"Antarctica"),
            array("country_id"=>"9","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Antigua and Barbuda"),
            array("country_id"=>"10","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Argentina"),
            array("country_id"=>"11","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"Armenia"),
            array("country_id"=>"12","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Aruba"),
            array("country_id"=>"13","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Australia"),
            array("country_id"=>"14","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Austria"),
            array("country_id"=>"15","utc"=>"4","region"=>"South Asia","continent"=>"Asia","name"=>"Azerbaijan"),
            array("country_id"=>"16","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Bahamas"),
            array("country_id"=>"17","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Bahrain"),
            array("country_id"=>"18","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"Bangladesh"),
            array("country_id"=>"19","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Barbados"),
            array("country_id"=>"20","utc"=>"3","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Belarus"),
            array("country_id"=>"21","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Belgium"),
            array("country_id"=>"22","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Belize"),
            array("country_id"=>"23","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Benin"),
            array("country_id"=>"24","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Bermuda"),
            array("country_id"=>"25","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"Bhutan"),
            array("country_id"=>"26","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Bolivia"),
            array("country_id"=>"27","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Bosnia and Herzegovina"),
            array("country_id"=>"28","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Botswana"),
            array("country_id"=>"29","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Brazil"),
            array("country_id"=>"30","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"British Indian Ocean Territory"),
            array("country_id"=>"31","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"British Virgin Islands"),
            array("country_id"=>"32","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Brunei"),
            array("country_id"=>"33","utc"=>"2","region"=>"South East Europe","continent"=>"Europe","name"=>"Bulgaria"),
            array("country_id"=>"34","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Burkina Faso"),
            array("country_id"=>"35","utc"=>"2","region"=>"Central Africa","continent"=>"Africa","name"=>"Burundi"),
            array("country_id"=>"36","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Cambodia"),
            array("country_id"=>"37","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Cameroon"),
            array("country_id"=>"38","utc"=>"-5","region"=>"North America","continent"=>"Americas","name"=>"Canada"),
            array("country_id"=>"39","utc"=>"-1","region"=>"Western Africa","continent"=>"Africa","name"=>"Cape Verde"),
            array("country_id"=>"40","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Cayman Islands"),
            array("country_id"=>"41","utc"=>"1","region"=>"Central Africa","continent"=>"Africa","name"=>"Central African Republic"),
            array("country_id"=>"42","utc"=>"1","region"=>"Central Africa","continent"=>"Africa","name"=>"Chad"),
            array("country_id"=>"43","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Chile"),
            array("country_id"=>"44","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"China"),
            array("country_id"=>"45","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Christmas Island"),
            array("country_id"=>"46","utc"=>"6","region"=>"South East Asia","continent"=>"Asia","name"=>"Cocos Islands"),
            array("country_id"=>"47","utc"=>"-5","region"=>"South America","continent"=>"Americas","name"=>"Colombia"),
            array("country_id"=>"48","utc"=>"3","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Comoros"),
            array("country_id"=>"49","utc"=>"-10","region"=>"Pacific","continent"=>"Oceania","name"=>"Cook Islands"),
            array("country_id"=>"50","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Costa Rica"),
            array("country_id"=>"51","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Croatia"),
            array("country_id"=>"52","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Cuba"),
            array("country_id"=>"53","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Curacao"),
            array("country_id"=>"54","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Cyprus"),
            array("country_id"=>"55","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Czech Republic"),
            array("country_id"=>"56","utc"=>"1","region"=>"West Indies","continent"=>"Americas","name"=>"Democratic Republic of the Congo"),
            array("country_id"=>"57","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Denmark"),
            array("country_id"=>"58","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Djibouti"),
            array("country_id"=>"59","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Dominica"),
            array("country_id"=>"60","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Dominican Republic"),
            array("country_id"=>"61","utc"=>"9","region"=>"Pacific","continent"=>"Oceania","name"=>"East Timor"),
            array("country_id"=>"62","utc"=>"-5","region"=>"South America","continent"=>"Americas","name"=>"Ecuador"),
            array("country_id"=>"63","utc"=>"2","region"=>"Northern Africa","continent"=>"Africa","name"=>"Egypt"),
            array("country_id"=>"64","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"El Salvador"),
            array("country_id"=>"65","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Equatorial Guinea"),
            array("country_id"=>"66","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Eritrea"),
            array("country_id"=>"67","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Estonia"),
            array("country_id"=>"68","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Ethiopia"),
            array("country_id"=>"69","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Falkland Islands"),
            array("country_id"=>"70","utc"=>"0","region"=>"Northern Europe","continent"=>"Europe","name"=>"Faroe Islands"),
            array("country_id"=>"71","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Fiji"),
            array("country_id"=>"72","utc"=>"2","region"=>"Northern Europe","continent"=>"Europe","name"=>"Finland"),
            array("country_id"=>"73","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"France"),
            array("country_id"=>"74","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"French Guiana"),
            array("country_id"=>"75","utc"=>"-10","region"=>"Pacific","continent"=>"Oceania","name"=>"French polynesia"),
            array("country_id"=>"76","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Gabon"),
            array("country_id"=>"77","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Gambia"),
            array("country_id"=>"78","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"Georgia"),
            array("country_id"=>"79","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Germany"),
            array("country_id"=>"80","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Ghana"),
            array("country_id"=>"81","utc"=>"1","region"=>"South West Europe","continent"=>"Europe","name"=>"Gibraltar"),
            array("country_id"=>"82","utc"=>"2","region"=>"South East Europe","continent"=>"Europe","name"=>"Greece"),
            array("country_id"=>"83","utc"=>"-4","region"=>"North America","continent"=>"Americas","name"=>"Greenland"),
            array("country_id"=>"84","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Grenada"),
            array("country_id"=>"85","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Guam"),
            array("country_id"=>"86","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Guatemala"),
            array("country_id"=>"87","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Guernsey"),
            array("country_id"=>"88","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Guinea"),
            array("country_id"=>"89","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Guinea-Bissau"),
            array("country_id"=>"90","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Guyana"),
            array("country_id"=>"91","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Haiti"),
            array("country_id"=>"92","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Honduras"),
            array("country_id"=>"93","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"Hong Kong"),
            array("country_id"=>"94","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Hungary"),
            array("country_id"=>"95","utc"=>"0","region"=>"Northern Europe","continent"=>"Europe","name"=>"Iceland"),
            array("country_id"=>"96","utc"=>"5","region"=>"South Asia","continent"=>"Asia","name"=>"India"),
            array("country_id"=>"97","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Indonesia"),
            array("country_id"=>"98","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Iran"),
            array("country_id"=>"99","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Iraq"),
            array("country_id"=>"100","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Ireland"),
            array("country_id"=>"101","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Isle of Man"),
            array("country_id"=>"102","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Israel"),
            array("country_id"=>"103","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Italy"),
            array("country_id"=>"104","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Ivory Coast"),
            array("country_id"=>"105","utc"=>"-5","region"=>"West Indies","continent"=>"Americas","name"=>"Jamaica"),
            array("country_id"=>"106","utc"=>"9","region"=>"East Asia","continent"=>"Asia","name"=>"Japan"),
            array("country_id"=>"107","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"Jersey"),
            array("country_id"=>"108","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Jordan"),
            array("country_id"=>"109","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Kazakhstan"),
            array("country_id"=>"110","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Kenya"),
            array("country_id"=>"111","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Kiribati"),
            array("country_id"=>"112","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Kosovo"),
            array("country_id"=>"113","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Kuwait"),
            array("country_id"=>"114","utc"=>"6","region"=>"Central Asia","continent"=>"Asia","name"=>"Kyrgyzstan"),
            array("country_id"=>"115","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Laos"),
            array("country_id"=>"116","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Latvia"),
            array("country_id"=>"117","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Lebanon"),
            array("country_id"=>"118","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Lesotho"),
            array("country_id"=>"119","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Liberia"),
            array("country_id"=>"120","utc"=>"2","region"=>"Northern Africa","continent"=>"Africa","name"=>"Libya"),
            array("country_id"=>"121","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Liechtenstein"),
            array("country_id"=>"122","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Lithuania"),
            array("country_id"=>"123","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Luxembourg"),
            array("country_id"=>"124","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"Macao"),
            array("country_id"=>"125","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Macedonia"),
            array("country_id"=>"126","utc"=>"3","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Madagascar"),
            array("country_id"=>"127","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Malawi"),
            array("country_id"=>"128","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Malaysia"),
            array("country_id"=>"129","utc"=>"5","region"=>"South Asia","continent"=>"Asia","name"=>"Maldives"),
            array("country_id"=>"130","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Mali"),
            array("country_id"=>"131","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Malta"),
            array("country_id"=>"132","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Marshall Islands"),
            array("country_id"=>"133","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Mauritania"),
            array("country_id"=>"134","utc"=>"4","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Mauritius"),
            array("country_id"=>"135","utc"=>"3","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Mayotte"),
            array("country_id"=>"136","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Mexico"),
            array("country_id"=>"137","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"Micronesia"),
            array("country_id"=>"138","utc"=>"2","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Moldova"),
            array("country_id"=>"139","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Monaco"),
            array("country_id"=>"140","utc"=>"7","region"=>"Northern Asia","continent"=>"Asia","name"=>"Mongolia"),
            array("country_id"=>"141","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Montenegro"),
            array("country_id"=>"142","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Montserrat"),
            array("country_id"=>"143","utc"=>"0","region"=>"Northern Africa","continent"=>"Africa","name"=>"Morocco"),
            array("country_id"=>"144","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Mozambique"),
            array("country_id"=>"145","utc"=>"6","region"=>"South East Asia","continent"=>"Asia","name"=>"Myanmar"),
            array("country_id"=>"146","utc"=>"1","region"=>"Southern Africa","continent"=>"Africa","name"=>"Namibia"),
            array("country_id"=>"147","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Nauru"),
            array("country_id"=>"148","utc"=>"6","region"=>"South Asia","continent"=>"Asia","name"=>"Nepal"),
            array("country_id"=>"149","utc"=>"1","region"=>"Western europe","continent"=>"Europe","name"=>"Netherlands"),
            array("country_id"=>"150","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Netherlands Antilles"),
            array("country_id"=>"151","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"New Caledonia"),
            array("country_id"=>"152","utc"=>"-11","region"=>"Pacific","continent"=>"Oceania","name"=>"New Zealand"),
            array("country_id"=>"153","utc"=>"-6","region"=>"Central America","continent"=>"Americas","name"=>"Nicaragua"),
            array("country_id"=>"154","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Niger"),
            array("country_id"=>"155","utc"=>"1","region"=>"Western Africa","continent"=>"Africa","name"=>"Nigeria"),
            array("country_id"=>"156","utc"=>"-11","region"=>"Pacific","continent"=>"Oceania","name"=>"Niue"),
            array("country_id"=>"157","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"North Korea"),
            array("country_id"=>"158","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Northern Mariana Islands"),
            array("country_id"=>"159","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Norway"),
            array("country_id"=>"160","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"Oman"),
            array("country_id"=>"161","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Pakistan"),
            array("country_id"=>"162","utc"=>"9","region"=>"Pacific","continent"=>"Oceania","name"=>"Palau"),
            array("country_id"=>"163","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Palestine"),
            array("country_id"=>"164","utc"=>"-5","region"=>"Central America","continent"=>"Americas","name"=>"Panama"),
            array("country_id"=>"165","utc"=>"10","region"=>"Pacific","continent"=>"Oceania","name"=>"Papua New Guinea"),
            array("country_id"=>"166","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Paraguay"),
            array("country_id"=>"167","utc"=>"-5","region"=>"South America","continent"=>"Americas","name"=>"Peru"),
            array("country_id"=>"168","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Philippines"),
            array("country_id"=>"169","utc"=>"-8","region"=>"Pacific","continent"=>"Oceania","name"=>"Pitcairn"),
            array("country_id"=>"170","utc"=>"1","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Poland"),
            array("country_id"=>"171","utc"=>"-1","region"=>"South West Europe","continent"=>"Europe","name"=>"Portugal"),
            array("country_id"=>"172","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Puerto Rico"),
            array("country_id"=>"173","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Qatar"),
            array("country_id"=>"174","utc"=>"1","region"=>"Central Africa","continent"=>"Africa","name"=>"Republic of the Congo"),
            array("country_id"=>"175","utc"=>"4","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Reunion"),
            array("country_id"=>"176","utc"=>"2","region"=>"South East Europe","continent"=>"Europe","name"=>"Romania"),
            array("country_id"=>"177","utc"=>"3","region"=>"Northern Asia","continent"=>"Asia","name"=>"Russia"),
            array("country_id"=>"178","utc"=>"2","region"=>"Central Asia","continent"=>"Africa","name"=>"Rwanda"),
            array("country_id"=>"179","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"Saint Barthelemy"),
            array("country_id"=>"180","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Saint Helena"),
            array("country_id"=>"181","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Saint Kitts and Nevis"),
            array("country_id"=>"182","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Saint Lucia"),
            array("country_id"=>"183","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"Saint Martin"),
            array("country_id"=>"184","utc"=>"-3","region"=>"Undecided","continent"=>"Americas","name"=>"Saint Pierre and Miquelon"),
            array("country_id"=>"185","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Saint Vincent and the Grenadines"),
            array("country_id"=>"186","utc"=>"13","region"=>"Pacific","continent"=>"Oceania","name"=>"Samoa"),
            array("country_id"=>"187","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"San Marino"),
            array("country_id"=>"188","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Sao Tome and Principe"),
            array("country_id"=>"189","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Saudi Arabia"),
            array("country_id"=>"190","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Senegal"),
            array("country_id"=>"191","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Serbia"),
            array("country_id"=>"192","utc"=>"4","region"=>"Indian Ocean","continent"=>"Africa","name"=>"Seychelles"),
            array("country_id"=>"193","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Sierra Leone"),
            array("country_id"=>"194","utc"=>"8","region"=>"South East Asia","continent"=>"Asia","name"=>"Singapore"),
            array("country_id"=>"195","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"Sint Maarten"),
            array("country_id"=>"196","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Slovakia"),
            array("country_id"=>"197","utc"=>"1","region"=>"South East Europe","continent"=>"Europe","name"=>"Slovenia"),
            array("country_id"=>"198","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"Solomon Islands"),
            array("country_id"=>"199","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Somalia"),
            array("country_id"=>"200","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"South Africa"),
            array("country_id"=>"201","utc"=>"9","region"=>"East Asia","continent"=>"Asia","name"=>"South Korea"),
            array("country_id"=>"202","utc"=>"3","region"=>"Northern Africa","continent"=>"Africa","name"=>"South Sudan"),
            array("country_id"=>"203","utc"=>"1","region"=>"South West Europe","continent"=>"Europe","name"=>"Spain"),
            array("country_id"=>"204","utc"=>"5","region"=>"South Asia","continent"=>"Asia","name"=>"Sri Lanka"),
            array("country_id"=>"205","utc"=>"3","region"=>"Northern Africa","continent"=>"Africa","name"=>"Sudan"),
            array("country_id"=>"206","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Suriname"),
            array("country_id"=>"207","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Svalbard and Jan Mayen"),
            array("country_id"=>"208","utc"=>"2","region"=>"Northern Africa","continent"=>"Africa","name"=>"Swaziland"),
            array("country_id"=>"209","utc"=>"1","region"=>"Northern Europe","continent"=>"Europe","name"=>"Sweden"),
            array("country_id"=>"210","utc"=>"1","region"=>"Central Europe","continent"=>"Europe","name"=>"Switzerland"),
            array("country_id"=>"211","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Syria"),
            array("country_id"=>"212","utc"=>"8","region"=>"East Asia","continent"=>"Asia","name"=>"Taiwan"),
            array("country_id"=>"213","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Tajikistan"),
            array("country_id"=>"214","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Tanzania"),
            array("country_id"=>"215","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Thailand"),
            array("country_id"=>"216","utc"=>"0","region"=>"Western Africa","continent"=>"Africa","name"=>"Togo"),
            array("country_id"=>"217","utc"=>"13","region"=>"Pacific","continent"=>"Oceania","name"=>"Tokelau"),
            array("country_id"=>"218","utc"=>"13","region"=>"Pacific","continent"=>"Oceania","name"=>"Tonga"),
            array("country_id"=>"219","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Trinidad and Tobago"),
            array("country_id"=>"220","utc"=>"1","region"=>"Northern Africa","continent"=>"Africa","name"=>"Tunisia"),
            array("country_id"=>"221","utc"=>"2","region"=>"South West Asia","continent"=>"Asia","name"=>"Turkey"),
            array("country_id"=>"222","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Turkmenistan"),
            array("country_id"=>"223","utc"=>"-4","region"=>"West Indies","continent"=>"Americas","name"=>"Turks and Caicos Islands"),
            array("country_id"=>"224","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Tuvalu"),
            array("country_id"=>"225","utc"=>"-4","region"=>"Central America","continent"=>"Americas","name"=>"U.S. Virgin Islands"),
            array("country_id"=>"226","utc"=>"3","region"=>"Eastern Africa","continent"=>"Africa","name"=>"Uganda"),
            array("country_id"=>"227","utc"=>"3","region"=>"Eastern Europe","continent"=>"Europe","name"=>"Ukraine"),
            array("country_id"=>"228","utc"=>"4","region"=>"South West Asia","continent"=>"Asia","name"=>"United Arab Emirates"),
            array("country_id"=>"229","utc"=>"0","region"=>"Western europe","continent"=>"Europe","name"=>"United Kingdom"),
            array("country_id"=>"230","utc"=>"-5","region"=>"North America","continent"=>"Americas","name"=>"United States"),
            array("country_id"=>"231","utc"=>"-3","region"=>"South America","continent"=>"Americas","name"=>"Uruguay"),
            array("country_id"=>"232","utc"=>"5","region"=>"Central Asia","continent"=>"Asia","name"=>"Uzbekistan"),
            array("country_id"=>"233","utc"=>"11","region"=>"Pacific","continent"=>"Oceania","name"=>"Vanuatu"),
            array("country_id"=>"234","utc"=>"1","region"=>"Southern Europe","continent"=>"Europe","name"=>"Vatican"),
            array("country_id"=>"235","utc"=>"-4","region"=>"South America","continent"=>"Americas","name"=>"Venezuela"),
            array("country_id"=>"236","utc"=>"7","region"=>"South East Asia","continent"=>"Asia","name"=>"Vietnam"),
            array("country_id"=>"237","utc"=>"12","region"=>"Pacific","continent"=>"Oceania","name"=>"Wallis and Futuna"),
            array("country_id"=>"238","utc"=>"0","region"=>"Northern Africa","continent"=>"Africa","name"=>"Western Sahara"),
            array("country_id"=>"239","utc"=>"3","region"=>"South West Asia","continent"=>"Asia","name"=>"Yemen"),
            array("country_id"=>"240","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Zambia"),
            array("country_id"=>"241","utc"=>"2","region"=>"Southern Africa","continent"=>"Africa","name"=>"Zimbabwe")
        );
        DB::table('countries')->insert($countries);
    }
}
